apiVersion: v1
kind: PersistentVolume
metadata:
  name: meu-pv-nfs
  labels:
    storage: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.23.54.113
    path: /mnt/nfs
  storageClassName: nfs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube-m02
