apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: meu-nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service # Tipo do objeto, no caso, um Service
metadata:
  name: nginx-service
spec:
  selector: # Seleciona os Pods que serão expostos pelo Service
    app: meu-nginx # Neste caso, os Pods com o label app=meu-app
  ports:
    - protocol: TCP
      port: 80 # Porta do Service
      targetPort: 8080 # Porta dos Pods
