apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: meu-nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: node-port-service
spec:
  type: NodePort # Tipo do Service
  selector:
    app: meu-nginx
  ports:
    - protocol: TCP
      port: 80 # Porta do Service, que será mapeada para a porta 8080 do Pod
      targetPort: 80 # Porta dos Pods
      nodePort: 30080   # Porta do Node, que será mapeada para a porta 80 do Service
