---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ingress-tls-pool
  namespace: metallb-system
spec:
  addresses:
    - 172.18.255.1-172.18.255.25
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ingress-tls-advertisement
  namespace: metallb-system
